
my_str = "hello, world, people"
my_str1 = "hello world people"
mi_nombre = "César"
print('Métodos o propiedades de un String en python')
# print(dir(my_str))

print(my_str.upper())
print(my_str.title())
print(my_str.lower())
print(my_str.swapcase())
print(my_str.capitalize())
print('Método encvadenado')
print(my_str.replace('hello', 'bye').upper())
print('Contando caracteres')
print(my_str.count('o'))
print('Verdadero o falso para saber si un texto ydenticando los caracteres inicia con cierta palabra')
print(my_str.startswith('hello'))
print(my_str.startswith('hola'))
print('Verdadero o falso para saber si un texto identicando los caracteres termina con cierta palabra')
print(my_str.endswith('world'))
print('Dividir un texto')
print("\n Separar caracteres y crear una lista")
print(my_str.split())
print('Une texto identificando un caracter')
print(my_str1.split(','))
print('Separa texto identificando un caracter, para el ejemplo la coma')
print(my_str.split(','))
print('Separa texto identificando un caracter, para el ejemplo la letra o')
print(my_str.split('o'))
print('Conocer la posicion de un cartacter')
print(my_str.find('o'))
print(my_str.find('l'))
print(len(my_str))
print('\tBuscar indice por caracter')
print(my_str.index('e'))
print('\tIdentificar tipo de caracter')
print(my_str.isnumeric())
print(my_str.isalpha())
print('\tImprimir según posción indicada viendo como arreglo un string')
print(my_str[4])
print('\tImprimir última posición indicada viendo como arreglo un string')
print(my_str[-1])
print(my_str[-10])

print('Mi nombre es: ' + mi_nombre)
print(f'Mi nombre es: {mi_nombre}')
print('Mi nombre es: {0}'.format(mi_nombre))

